services:
  - type: web
    name: ecommerce
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ecommerce.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: PYTHON_VERSION
        value: 3.11
    staticPublishPath: staticfiles
